// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package handler

import (
	"github.com/zeromicro/go-zero/rest"
	"net/http"
)

// 对go-zero原有的路由进行封装
type Routers struct {
	server      *rest.Server
	middlewares []rest.Middleware
	prefix      string
}

func NewRouters(server *rest.Server, prefix string) *Routers {
	return &Routers{
		server: server,
		prefix: prefix,
	}
}

func (r *Routers) Get(path string, handlerFunc http.HandlerFunc) {
	r.server.AddRoutes(
		rest.WithMiddlewares(
			r.middlewares,
			rest.Route{
				Method:  http.MethodGet,
				Path:    path,
				Handler: handlerFunc,
			},
		),
		//统一加个前缀
		rest.WithPrefix(r.prefix),
	)
}
func (r *Routers) Post(path string, handlerFunc http.HandlerFunc) {
	r.server.AddRoutes(
		rest.WithMiddlewares(
			r.middlewares,
			rest.Route{
				Method:  http.MethodPost,
				Path:    path,
				Handler: handlerFunc,
			},
		),
		rest.WithPrefix(r.prefix),
	)
}

func (r *Routers) GetNoPrefix(path string, handlerFunc http.HandlerFunc) {
	r.server.AddRoutes(
		rest.WithMiddlewares(
			r.middlewares,
			rest.Route{
				Method:  http.MethodGet,
				Path:    path,
				Handler: handlerFunc,
			},
		),
		//统一加个前缀
		rest.WithPrefix(r.prefix),
	)
}
func (r *Routers) PostNoprefix(path string, handlerFunc http.HandlerFunc) {
	r.server.AddRoutes(
		rest.WithMiddlewares(
			r.middlewares,
			rest.Route{
				Method:  http.MethodPost,
				Path:    path,
				Handler: handlerFunc,
			},
		),
		rest.WithPrefix(r.prefix),
	)
}

func (r *Routers) Group() *Routers {
	return &Routers{
		server: r.server,
		prefix: r.prefix,
	}
}

func (r *Routers) Use(middlewares ...rest.Middleware) {
	r.middlewares = middlewares
}
